### ISSUE TITLE
Dependency lxml not listed nor installed automatically

### ISSUE THREAD

**Issue by Saijin-Naib** [opengisch/qgis_trackable_project_files#1]
2019-04-09T10:25:13     WARNING    Traceback (most recent call last):
              File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 309, in loadPlugin
              __import__(packageName)
              File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/bcarlock/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\trackable_project_files\__init__.py", line 13, in 
              import lxml.etree as ET
              File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ModuleNotFoundError: No module named 'lxml'

**Comment by mbernasocchi** [comment]
you need to install lxml.
from the qgis python console in windows you can try
 ``` 
import subprocess
subprocess.check_call(['python3', '-m', 'pip', 'install', 'lxml'])
```
in linux `pip3 install lxml` or similar

**Comment by Saijin-Naib** [comment]
Yep! I installed it using the above method. If possible, having the dependency modules listed would be super helpful as I wasn't too familiar/comfortable reading the debug info to figure out what module I had missing.

Thanks for this great plugin!

**Comment by mstuyts** [comment]
lxml is now added to the OSGeo4W installer: https://trac.osgeo.org/osgeo4w/ticket/226#comment:5

**Comment by m-kuhn** [comment]
> Yep! I installed it using the above method. If possible, having the dependency modules listed would be super helpful as I wasn't too familiar/comfortable reading the debug info to figure out what module I had missing.

What is the above method?

The python console command or the `pip3 install` command?

If someone has a method that can be triggered automatically from Python on a Windows machine (working in osgeo4w and standalone installations) that would help a lot.

**Comment by Saijin-Naib** [comment]
Manual install of lxml with .\python.exe -m pip install lxml

**Comment by kalakaru** [comment]
@Saijin-Naib Which .\python.exe did you use? There are several on my windows machine when I search for python.exe in the QGIS 3.4 installation: 

![grafik](https://user-images.githubusercontent.com/40888097/68375021-50040280-0146-11ea-9c85-d68beab6d8d5.png)

**Comment by Saijin-Naib** [comment]
@kalakaru ,

I used the python.exe in this path:
`C:\OSGeo4W64\apps\Python37\python.exe`

![image](https://user-images.githubusercontent.com/19295950/68397215-d1589680-0140-11ea-8e71-a90008a7654f.png)

This is the OSGeo4W installed python runtime used by QGIS.
![image](https://user-images.githubusercontent.com/19295950/68397256-e3d2d000-0140-11ea-9dd6-d0f712047ce6.png)

**Comment by ponceta** [comment]
![image](https://user-images.githubusercontent.com/8614223/99644778-a2147f00-2a4e-11eb-8a09-b7f23c774df6.png)

Its name is python3-lxml if you search it like I did for QGIS3.10 and later, will add it to my default installation commandline.

**Comment by ponceta** [comment]
IMHO a human readable dependency list would be sufficient if directly available on the plugin repository message :

![image](https://user-images.githubusercontent.com/8614223/99775484-a05ec000-2b0f-11eb-8bde-7b1e63961fc2.png)

That would be a nice QGIS plugin repo enhancement. (instead of having it the hard way everytime you try and catch dependencies errors messages)

**Comment by m-kuhn** [comment]
IMO we could start with a list of dependencies in the metadata or in a requirements.txt file. This could be listed as you say.
And in a further step it could propose to `pip` it in. @olivierdalang has started to think about this too (and he's not the only one :D ).

**Comment by lindacamathias** [comment]
This is still the case (by @suricactus) on windows 10, qgis 3.16:
```
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Linda/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\trackable_project_files\__init__.py", line 13, in 
    import lxml.etree as ET
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'lxml'
```
