### ISSUE TITLE
Uncaught UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 4799: ordinal not in range(128)


### ISSUE THREAD

**Issue by baditaflorin** [opengisch/qgis_trackable_project_files#14]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "/Users/florin/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/trackable_project_files/__init__.py", line 34, in normalize_xml
    et = ET.parse(file)
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1880, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1900, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1795, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1201, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 721, in lxml.etree._handleParseResult
  File "src/lxml/etree.pyx", line 318, in lxml.etree._ExceptionContext._raise_if_stored
  File "src/lxml/parser.pxi", line 370, in lxml.etree._FileReaderContext.copyToBuffer
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 4799: ordinal not in range(128)

```
trackable_project_files 1.2.0, QGIS 3.14.16-Pi on Darwin 19.6.0

**Comment by m-kuhn** [comment]
Related to https://github.com/opengisch/qgis_trackable_project_files/issues/2

**Comment by andreasneumann** [comment]
I also seem to have unicode/ascii problems with this plugin.

QGIS 3.10 projects saved within 3.16 and the trackable plugin active destroys any special characters in layer names and legend entries.

Maybe you have to do somehting similar like in this commit in the SoLocator plugin: https://github.com/opengisch/solocator/commit/03964748e282d094b9b25cdd2e95b7ca78cd50f1
