### ISSUE TITLE
UnicodeDecodeError upon project save

### ISSUE THREAD

**Issue by Saijin-Naib** [opengisch/qgis_trackable_project_files#2]
2019-04-09T10:26:12     WARNING    Traceback (most recent call last):
              File "C:/Users/bcarlock/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\trackable_project_files\__init__.py", line 27, in normalize_xml
              et = ET.parse(file)
              File "src\lxml\etree.pyx", line 3435, in lxml.etree.parse
              File "src\lxml\parser.pxi", line 1861, in lxml.etree._parseDocument
              File "src\lxml\parser.pxi", line 1881, in lxml.etree._parseFilelikeDocument
              File "src\lxml\parser.pxi", line 1776, in lxml.etree._parseDocFromFilelike
              File "src\lxml\parser.pxi", line 1187, in lxml.etree._BaseParser._parseDocFromFilelike
              File "src\lxml\parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
              File "src\lxml\parser.pxi", line 707, in lxml.etree._handleParseResult
              File "src\lxml\etree.pyx", line 314, in lxml.etree._ExceptionContext._raise_if_stored
              File "src\lxml\parser.pxi", line 370, in lxml.etree._FileReaderContext.copyToBuffer
              File "C:\OSGeo4W64\apps\Python37\lib\codecs.py", line 322, in decode
              (result, consumed) = self._buffer_decode(data, self.errors, final)
             UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 10: invalid start byte

**Comment by mstuyts** [comment]
I got a very similar error message:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xec in position 10: invalid continuation byte 
Traceback (most recent call last):
  File "C:/Users/michstuy/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\trackable_project_files\__init__.py", line 27, in normalize_xml
    et = ET.parse(file)
  File "src\lxml\etree.pyx", line 3435, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1861, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1881, in lxml.etree._parseFilelikeDocument
  File "src\lxml\parser.pxi", line 1776, in lxml.etree._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 1187, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 707, in lxml.etree._handleParseResult
  File "src\lxml\etree.pyx", line 314, in lxml.etree._ExceptionContext._raise_if_stored
  File "src\lxml\parser.pxi", line 370, in lxml.etree._FileReaderContext.copyToBuffer
  File "C:\OSGEO4~1\apps\Python37\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xec in position 10: invalid continuation byte
```

In QGIS 3.6.1 on Windows 10

**Comment by febs** [comment]
Experiencing this on Linux, QGIS 3.6.2

**Comment by Gustry** [comment]
Yes, I can replicate this issue too.
It's simple project that I can share, with one layer in it.

**Comment by m-kuhn** [comment]
A patch that fixes this will happily be accepted

**Comment by Saijin-Naib** [comment]
> A patch that fixes this will happily be accepted

I'm way out of my depth here, but what even is "this"? I don't understand what the error means or what is happening.

**Comment by m-kuhn** [comment]
I guess you need to take a look at this to get started https://stackoverflow.com/a/21698118/2319028

**Comment by Antanide** [comment]
"fix it yourself" is not an acceptable answer in an issue tracking system, not even in a completely open source project.

**Comment by m-kuhn** [comment]
Hi @Antanide 
This plugin was developed for our purpose where it works as expected. It was released for free in open source spirit in the hope that it will be useful for others too. And in the hope that others will contribute too and help to make it better. I understand that not everyone has the required know how to fix things himself, but we just have a limited amount of time to give too. So unfortunately we will need to push this back in our priority list until it's an issue for us, we suddenly have free time, someone comes forward with a fix for this or someone contracts us to fix it. I hope this does not come over disrespectful. I really hope that we will get a fix for this soon!

**Comment by tudorbarascu** [comment]
I had a similar problem and I solved it using vim, going to those specific lines and erasing the invalid characters. Maybe it won't solve this.. as it may not be exactly the same. For me it was ``version="^A"`` and I turned it into ``version=""`` Don't know if it helps. Thanks @m-kuhn for the plugin :).

**Comment by m-kuhn** [comment]
Thanks @andreasneumann for sponsoring this fix :tada:
