### ISSUE TITLE
Error while unloading plugin trackable_project_files 

### ISSUE THREAD

**Issue by signedav** [opengisch/qgis_trackable_project_files#5]
```
TypeError: argument 1 has unexpected type 'NoneType' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 390, in unloadPlugin
    plugins[packageName].unload()
  File "/home/david/.local/share/QGIS/QGIS3/profiles/default/python/plugins/trackable_project_files/__init__.py", line 34, in unload
    QgsProject.instance().projectSaved.disconnect(self.project_saved_connection)
TypeError: argument 1 has unexpected type 'NoneType'


Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0] 
QGIS version: 3.6.0-Noosa Noosa, 5873452 
```
Tell me if I should have a look at id.

**Comment by haubourg** [comment]
+1 I encounter this issue too with master also

**Comment by andreasneumann** [comment]
I have the very same issue. Always when closing QGIS:

`Error while unloading plugin trackable_project_files 

TypeError: argument 1 has unexpected type 'NoneType' 
Traceback (most recent call last):
  File "/usr/local/share/qgis/python/qgis/utils.py", line 434, in unloadPlugin
    plugins[packageName].unload()
  File "/home/bjsvwneu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/trackable_project_files/__init__.py", line 34, in unload
    QgsProject.instance().projectSaved.disconnect(self.project_saved_connection)
TypeError: argument 1 has unexpected type 'NoneType'


Python version: 3.6.8 (default, Aug 20 2019, 17:12:48) [GCC 8.3.0] 
QGIS version: 3.9.0-Master Master, 970e42b7f7 
`

**Comment by mdouchin** [comment]
I proposed the PR #8  to adresse this issue

**Comment by andreasneumann** [comment]
Apparently this happens only, if the open project wasn't saved on closing.

**Comment by mdouchin** [comment]
yes

**Comment by m-kuhn** [comment]
Should be fixed
